import struct
import setuptools
from pathlib import Path
from setuptools.command.build_py import build_py as _build_py
from setuptools.command.develop import develop as _develop


CURRENT_FOLDER = Path(__file__).parent
README_PATH = CURRENT_FOLDER / 'README.md'
ASM_DIR = CURRENT_FOLDER / 'asm'
SHELLCODES_PY = CURRENT_FOLDER / 'peor' / '_shellcodes.py'

# Magic placeholder used in reloc-resolver ASM to mark where the PE offset goes.
# After assembly the actual (shellcode_size - 5) is patched in.
_PE_OFFSET_PLACEHOLDER = b'\x7e\x7e\x7e\x7e'


def _assemble_shellcodes():
    """Assemble all ASM resolver sources into peor/_shellcodes.py via keystone."""
    import keystone

    def assemble(asm_path, arch, mode, patch_pe_offset=False):
        ks = keystone.Ks(arch, mode)
        ks.syntax = keystone.KS_OPT_SYNTAX_NASM
        src = Path(asm_path).read_text(encoding='utf-8')
        encoding, _ = ks.asm(src)
        if encoding is None:
            raise RuntimeError(f"keystone assembly failed for {asm_path}")
        result = bytearray(encoding)

        if patch_pe_offset:
            # The shellcode starts with "CALL _base" (5 bytes), then "POP reg" leaves
            # reg pointing to _base (offset 5 from start).  We want reg + offset = PE base.
            # PE base = shellcode_start + len(shellcode), so offset = len - 5.
            pe_offset = len(result) - 5
            idx = result.find(_PE_OFFSET_PLACEHOLDER)
            if idx == -1:
                raise RuntimeError(f"PE offset placeholder {_PE_OFFSET_PLACEHOLDER.hex()} not found in {asm_path}")
            result[idx:idx + 4] = struct.pack('<I', pe_offset)

        return bytes(result)

    r32 = assemble(ASM_DIR / 'relocations_resolver32.asm', keystone.KS_ARCH_X86, keystone.KS_MODE_32, patch_pe_offset=True)
    r64 = assemble(ASM_DIR / 'relocations_resolver64.asm', keystone.KS_ARCH_X86, keystone.KS_MODE_64, patch_pe_offset=True)
    i32 = assemble(ASM_DIR / 'imports_resolver32.asm',     keystone.KS_ARCH_X86, keystone.KS_MODE_32)
    i64 = assemble(ASM_DIR / 'imports_resolver64.asm',     keystone.KS_ARCH_X86, keystone.KS_MODE_64)

    SHELLCODES_PY.write_text(
        "# Auto-generated by setup.py -- do not edit. Re-run: pip install -e .\n"
        f"RELOCS_32     = bytes.fromhex('{r32.hex()}')\n"
        f"RELOCS_64     = bytes.fromhex('{r64.hex()}')\n"
        f"IMPORTS_32_UM = bytes.fromhex('{i32.hex()}')\n"
        f"IMPORTS_64_UM = bytes.fromhex('{i64.hex()}')\n",
        encoding='utf-8',
    )
    print(f"[peor] assembled shellcodes -> {SHELLCODES_PY}")


# Run assembly whenever setup.py is evaluated by pip (build env already has keystone).
# pyproject.toml lists keystone-engine in build-system.requires so it's always present here.
_assemble_shellcodes()


class build_py(_build_py):
    def run(self):
        _assemble_shellcodes()
        super().run()


class develop(_develop):
    def run(self):
        _assemble_shellcodes()
        super().run()


setuptools.setup(
    name='peor',
    version='1.0.0',
    author='Ariel Tubul',
    packages=setuptools.find_packages(),
    long_description=README_PATH.read_text(),
    install_requires=['pefile', 'keystone-engine'],
    long_description_content_type='text/markdown',
    url='https://github.com/mon231/peor/',
    description='PortableExecutable shellcodifier',
    entry_points={'console_scripts': ['peor=peor.__main__:main']},
    cmdclass={
        'build_py': build_py,
        'develop': develop,
    },
)
